### PR TITLE
Grammar: change amount to number

### PR DESCRIPTION
**Pull request by padiwik**
This has bothered me for a while

### CODE REVIEW

**Comment by Zamiell** [comment]
its clearer the way it is because "number" refers to a "number clue"

**Comment by padiwik** [comment]
It is clear that "number of clues" and "number clue" are distinct. It also sounds wrong when amount is used here (https://grammarist.com/usage/amount-number/)

**Comment by padiwik** [comment]
(and aside from the "different number of positive/negative clues" in the Order Chop Move section, there is no ambiguity from saying "number of cards", "number of players", etc)

**Comment by Zamiell** [comment]
```
* Different numbers of negative clues are ignored.
```
this is really confusing. it looks like it is talking about "negative 2", "negative 3", etc

**Comment by padiwik** [comment]
hmm i see.. can it just be "different negative clues" and still have the same meaning?

**Comment by Zamiell** [comment]
im not going to sacrifice clarity for grammar

**Comment by padiwik** [comment]
specifically for that OCM section: even as written it is a mouthful, so the phrasing should be simplified if possible

**Comment by Zamiell** [comment]
i dont think "different negative clues" is very clear

**Comment by padiwik** [comment]
currently ("different amount of negative clues"):
look at all the negative clues, count them, then see if the counts match

proposal ("different negative clues"):
look at all the negative clues and see if there are any differences

is the second not simpler? at least i don't see how it is less clear than what is written currently

**Comment by padiwik** [comment]
i may have misinterpreted the convention... Suppose Alice has two 1s, one of which is known to be red and the other known to be blue (same number of positive color clues). If she plays the wrong 1, this indicates an order chop move instead of a priority?

**Comment by Zamiell** [comment]
in a no variant game?

**Comment by padiwik** [comment]
yes

**Comment by Zamiell** [comment]
```
* Sometimes, after getting clued about two or more 1s, a player will receive a follow-up clue that "fills in" one or more of the 1s. In this situation, playing a 1 with the full identity revealed will not cause an *Order Chop Move*. In other words, *Order Chop Moves* can only happen when a player has two or more 1s with each 1 having two or more identities.
* Besides that, there are some other common situations that do **not** imply an *Order Chop Move*. Use your common sense! Here is a short list:
  * The 1 was expected to be played from the *[Fresh 1's Rule](#playing-multiple-1s---the-fresh-1s-rule-part-2)*.
  * The 1 was expected to be played from the *[Chop Focus Exception](#playing-multiple-1s---the-chop-focus-exception-part-3).
  * The 1 that was played has different positive clues than the other 1's.
    * Different negative clues are ignored.
  * The 1 that was played was originally *Finessed* from a clue that happened **before** the number 1 clue.
  * The 1 that was skipped over is known to be bad from contextual information. (See the *[Stale 1's Clue](#context-clues--the-stale-1s-clue)* section.)
```

**Comment by padiwik** [comment]
ok let me rebase off that

**Comment by padiwik** [comment]
check now

**Pull request merged**
