### PR TITLE
Proposal: Trash Push Charm, OOP Charm

### PR DESCRIPTION
**Pull request by 0nen**

### CODE REVIEW

**Comment by pianoblook** [comment]
If the _Pushed_ card is two or more away, why wouldn't this just call for an Ejection? 

Your example, Alice cluing red to Cathy, is not a trash push, because it is not already known Trash. Bob would need to Discharge and trust that it was a _Necessary UTD_

See #257 and #311

**Comment by pclinger** [comment]
In the example, red 5 is played on the stacks, so clueing red is known trash, and thus a trash push.

**Comment by 0nen** [comment]
In the example, red 5 is played on the stacks. A clue of red is most definitely a trash push.

**Comment by pianoblook** [comment]
Oh ok. well in that case it would not conflict with 5ce because it's already known trash

**Comment by Jayhui-q** [comment]
Agree with Piano's comment above. If it's known trash, the ejection is not a lie and is a clearer signal shift of play -> save/good card, and it is probably more likely that an ejection exists and is playable than for a charm. For 4 players or more you can always focus the charm slot if it exists, and you wouldn't be worried about the aforementioned good card being chopped.

I would be interested maybe if there's some always unnecessary component that gets two blind-plays from some clever maneuver like this, but otherwise, it doesn't seem that strong.

**Comment by 0nen** [comment]
There are so many ways to eject cards already, and right now there's no good way to Charm in the mid game. Once all the 1s are played, 4 Charm is gone, and Declined 5 Pull is only in the Low Score Phase.

Having more tools opens up options up for new play. Many times you are stuck in a position where you must 1-for-1 clue a chop card that is about to fall off. Something like this adds a scenario where you can still get that 4th finesse to play, and save another useful card, for later.

I feel like a trash push on a two-away-from-playable card is a scenario that could come up quite often in games. This could make it a very valuable tool for getting 4th finesse position, where we just don't have that option right now.

**Comment by Jayhui-q** [comment]
Haha, I think you would love to see the Junk Charm that Piano proposed then: 
https://github.com/Zamiell/hanabi-conventions/issues/399

I agree about having the new tools, but the charm moves the signal from play to play rather than from play to save. 
https://github.com/Zamiell/hanabi-conventions/blob/master/Reference.md#level-19---rarely-used-strategies---signal-shifting

In addition, in your example, an ejection would never be a lie. If it is known trash, ejecting does not make it read as a 5 (especially if you give a rank clue, which your proposal supports), and if it were unknown trash, then a finesse/discharge would be needed.

The reason we have more ejection tools than charm tools is precisely that the charm slot is less likely to exist or be playable. (A player with 4 cards in hand must have no cards clued at all for it to exist, and if we've let it go all the way to the charm slot, it must've not been playable for a long time). This is also why it makes sense that most of our charms happen in the low score phase.

I agree that a trash push on a two-away-from-playable comes up a lot, but I think the argument is that it should eject instead. This would protect the card on the chop that is about to fall off too! Otherwise, the usual solution to a card on slot 4 is just to give the save and then prompt it out later, which I don't think is that bad.

**Comment by pianoblook** [comment]
Trash Push Ejections have been proposed for many months.

This discussion from back in April (plus Jeff's linked doc) is a treasure trove of discussion

https://github.com/Zamiell/hanabi-conventions/issues/186

**Comment by Zamiell** [comment]
open an issue for convention proposals, not a pull request.
i will ask for a pull request if the proposal is accepted

**Pull request closed without merging**
