### PR TITLE
safety charm examples

### PR DESCRIPTION
**Pull request by pianoblook**
Something about the formatting isn't showing up correctly for me, but I tried to exactly copy the format of other example docs. Hope this works on your end

### CODE REVIEW

**Comment by Zamiell** [comment]
1) the file should be called Safety_Charm.md to match all of the other existing files
2) match the format of all of the existing images, dont just randomly create your own

**Review by pianoblook — COMMENTED** [review]
ooh maybe the .md fixed it all

**Comment by Zamiell** [comment]
?

**Comment by pianoblook** [comment]
ugh, so it seems to be failing because I included usernames (wortel, nydus, RJW, gnomesayin) that it doesn't recognize. I don't understand T_T

**Comment by Zamiell** [comment]
in vscode, right click on the word and select "add to workplace dictionary"

**Review by pianoblook — COMMENTED** [review]
changed names to Alice/Bob

**Comment by Zamiell** [comment]
the names must exactly match the names in the screenshot.
e.g. look at what all the other example pages and copy that format

**Review by pianoblook — COMMENTED** [review]
I'm so bad at this

**Comment by Zamiell** [comment]
perfect, thanks

**Pull request merged**
