### PR TITLE
Proposal: Shuffle levels so 5ce + 5pull come before prio + elim

### PR DESCRIPTION
**Pull request by vEnhance**
Implement the suggestion in last comment of #373

### CODE REVIEW

**Comment by Zamiell** [comment]
i think you forgot table of contents, correct me if i am wrong

**Comment by vEnhance** [comment]
> i think you forgot table of contents, correct me if i am wrong

Assuming you're referring to ToC at start of `Reference.md`, I don't think that table of contents needs to change because I left the names of the levels intact (journeyman, advanced, adept, .senior).

**Comment by Zamiell** [comment]
you're right

**Comment by Zamiell** [comment]
thanks

**Pull request merged**
