### PR TITLE
Add the other links to convention reasons

### PR DESCRIPTION
**Pull request by padiwik**

### CODE REVIEW

**Comment by Zamiell** [comment]
I guess not

**Comment by padiwik** [comment]
why not

**Comment by Zamiell** [comment]
because of what you said in the other thread

**Comment by padiwik** [comment]
i changed my mind, i think this version is ok. at least for the 3 bluffs. i guess you don't want to clutter the beginner doc?

**Comment by Zamiell** [comment]
this pr adds clutter

**Comment by padiwik** [comment]
are people expected to browse the repo and find the convention_reasons doc? or just we link the doc when someone asks a pertinent question?

**Comment by Zamiell** [comment]
either one

**Pull request closed without merging**
