### PR TITLE
Clarify LHS stall priority

### PR DESCRIPTION
**Pull request by padiwik**

### CODE REVIEW

**Comment by Zamiell** [comment]
you added a bullet point mentioning LHS, but LHS is not defined yet at that point in the document

**Comment by padiwik** [comment]
that complaint doesn't make sense when it's present in the table above

**Comment by padiwik** [comment]
Maybe a better solution is to define LHS, 8 Clue Save, and Filling in info as having the same precedence? Since technically you can decline to perform an 8 clue save and fill in info instead

**Comment by Zamiell** [comment]
> Maybe a better solution is to define LHS, 8 Clue Save, and Filling in info as having the same precedence?

that kind of deletes all of the columns then

**Comment by Zamiell** [comment]
ok i updated the doc, let me know if this good

**Comment by padiwik** [comment]
seems ok, I'd appreciate having the note on why they're tied but it's not strictly necessary.

actually now I'm thinking about the edge case where a lhs is available but no fill ins. Alice does a hard burn because she doesn't want to LHS, so technically the priority table is wrong. but it's good enough

**Pull request closed without merging**
