### PR TITLE
Clarify Delayed Play Clues

### PR DESCRIPTION
**Pull request by padiwik**
There was a beginner confused about this. The example was not very concrete beforehand, anyways.

### CODE REVIEW

**Comment by Zamiell** [comment]
don't use yellow

the convention in the doc is to use red, then blue, then green

**Comment by padiwik** [comment]
you mean red, green, blue?

**Comment by Zamiell** [comment]
nope, red, blue, then green

**Comment by padiwik** [comment]
Huh, why? But fixed

**Comment by Zamiell** [comment]
thats the order that colors are assigned on the website

**Comment by padiwik** [comment]
Oh yeah because a game with 2 normal suits is just red and blue, right

**Comment by Zamiell** [comment]
yup

**Comment by Zamiell** [comment]
i updated the doc to be more clear

**Pull request closed without merging**
